[pytest]
## Global CLI arguments
addopts = --headed --browser chromium --browser webkit --browser firefox --screenshot=only-on-failure --video=retain-on-failure --alluredir=allure-results

## Test file location
testpaths = tests

## Naming covention for test discovery
python_files = test_*.py
python_functions = test_*
python_classes = Test*

## Custom markers for grouping tests 
markers = 
    smoke: Critical path tests
    regression: Full suite tests